services:
  - type: web
    name: rental-car-api
    runtime: docker
    region: oregon
    plan: starter

    dockerContext: ./projectswp391
    dockerfilePath: ./projectswp391/Dockerfile

    envVars:
      - key: SPRING_APPLICATION_NAME
        value: Rental_Car

      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d3qdp0u3jp1c738hue5g-a:5432/rental_car_fkui
      - key: SPRING_DATASOURCE_USERNAME
        value: rental_car_fkui_user
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false   # nhập password trong Dashboard sau khi deploy

      # JPA / pool
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: none
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
      - key: DB_POOL_MAX
        value: "5"
      - key: DB_POOL_MIN
        value: "2"

      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        value: "true"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        value: "true"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT
        value: "5000"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT
        value: "5000"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT
        value: "5000"

      - key: JWT_ACCESSKEY
        sync: false
      - key: JWT_REFRESHKEY
        sync: false
      - key: JWT_ACCESSEXPIRATION
        value: "900000"
      - key: JWT_REFRESHEXPIRATION
        value: "604800000"
      - key: VNP_URL
        value: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - key: VNP_RETURNURL
        value: https://rental-car-api.onrender.com/api/payment/vnpay-callback
      - key: VNP_TMNCODE
        sync: false
      - key: VNP_HASHSECRET
        sync: false
